"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var vector_1 = require("./vector");
var elements = new vector_1.Vector(3, 5);
var vector = new vector_1.Vector(4, 6);
console.log(vector.print());
console.log(elements.add(vector));
console.log(elements.subs(vector));
console.log(elements.mult(vector));
console.log(elements.multNumber(3));
